language: elixir
elixir:
  - 1.2.3
otp_release:
  - 18.3

before_script:
  - cp config/travis_test.exs config/test.exs
  - mix ecto.create
  - mix ecto.migrate

services:
  - postgresql

addons:
  postgresql: "9.4"

env:
  - TEST_VARIABLE=IAMSET